spring:
  devtools:
    livereload:
      enabled: true
  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    url: jdbc:h2:mem:blogSearch
    username: lee_sm
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  thymeleaf:
    prefix: classpath:templates/
    check-template-location: true
    suffix: .html
    cache: false

logging.level:
  org.hibernate.SQL: debug

blogApi:
  kakao:
    url: https://dapi.kakao.com/v2/search/blog
    key: KakaoAK 5af66e30ba41c094d3c62bf8cfff6d36

  naver:
    url: https://openapi.naver.com/v1/search/blog.json
    clientId: BeGz6Mvxh7bDArnW3ADX
    clientSecret: g7fkhZB1vu